# Generated by Django 6.0.2 on 2026-02-18 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_review_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='contry',
            new_name='country',
        ),
    ]
