# Generated by Django 6.0.2 on 2026-02-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_contry_movie_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Video URL'),
        ),
    ]
